In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
torch.__version__


'2.7.1+cu128'

In [3]:
torch.cuda.is_available()
torch.cuda.device_count()

1

### Understanding Tensors

In [4]:
# scalar - 0 dim tensor
scalar = torch.tensor(6)
print(f"The tensor is of {scalar.ndim} dim")

The tensor is of 0 dim


In [5]:
scalar.item() # retrieves the number

6

In [6]:
vector = torch.tensor([2,3])
vector.shape         # hint: the num of dims is the num of brackets

torch.Size([2])

In [7]:
mat = torch.tensor([[1,2],
                    [3,4]])
mat.shape

torch.Size([2, 2])

In [8]:
ten = torch.tensor([[[1, 2, 2],
                    [3, 4, 3]]])
ten.shape  # goes from outer to inner

torch.Size([1, 2, 3])

Reminder: Tensor is an n dimsional array of numbers. So matrix, vectors, scalars are also tensors of different dims

In [9]:
ten

tensor([[[1, 2, 2],
         [3, 4, 3]]])

In [10]:
# creating a random tensor
rand_T = torch.rand((3,3))
rand_T

tensor([[0.3736, 0.6964, 0.1051],
        [0.5714, 0.4450, 0.9078],
        [0.6610, 0.4604, 0.4544]])

In [41]:
IM = torch.rand((224, 224, 3))
IM

tensor([[[0.9107, 0.6741, 0.5522],
         [0.9034, 0.7437, 0.1018],
         [0.2668, 0.6009, 0.3164],
         ...,
         [0.5212, 0.6690, 0.1890],
         [0.6228, 0.0231, 0.1559],
         [0.3312, 0.6335, 0.4917]],

        [[0.4033, 0.2725, 0.2969],
         [0.2007, 0.3289, 0.3674],
         [0.4146, 0.9103, 0.1782],
         ...,
         [0.5753, 0.9120, 0.8689],
         [0.2940, 0.9637, 0.3804],
         [0.1678, 0.6532, 0.7502]],

        [[0.2731, 0.5788, 0.4707],
         [0.3459, 0.7599, 0.9259],
         [0.2881, 0.3427, 0.4572],
         ...,
         [0.6316, 0.1327, 0.4598],
         [0.8130, 0.1432, 0.9286],
         [0.0583, 0.6763, 0.8814]],

        ...,

        [[0.7460, 0.6659, 0.1520],
         [0.8776, 0.4305, 0.3846],
         [0.0848, 0.9501, 0.2881],
         ...,
         [0.7392, 0.9697, 0.3718],
         [0.5834, 0.9700, 0.3800],
         [0.5916, 0.1115, 0.6508]],

        [[0.7291, 0.2762, 0.2910],
         [0.7094, 0.4959, 0.0817],
         [0.

In [52]:
tem = torch.arange(0, 101, 20, dtype = None)
print(tem)
co = torch.ones_like(tem)

tensor([  0,  20,  40,  60,  80, 100])


In [51]:
co

tensor([1, 1, 1, 1, 1, 1])

1. torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

2. Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

3. torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

4. torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

5. torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
torch.permute(input, dims)

6. torch.permute(input, dims) Rearrange the axis order

In [85]:
x = torch.arange(1, 20, 2)
x.shape

torch.Size([10])

In [88]:
x = x.reshape(5,2)

In [73]:
z = x.view(10,1)        # z is just a new view of x and changing z changes x
z

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])

In [74]:
print(f"Before squeeze the dims was {z.shape}")

k = z.squeeze()     # removes single dims
print(f"after sqeeze the dims: {k.shape}, the singles dims were removed")

Before squeeze the dims was torch.Size([10, 1])
after sqeeze the dims: torch.Size([10]), the singles dims were removed


In [94]:
print(f"Before permuting {x}\n")


print(f"after permuting {x.permute(1,0)}")

Before permuting tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]])

after permuting tensor([[ 1,  5,  9, 13, 17],
        [ 3,  7, 11, 15, 19]])


tensor([[ 1,  5,  9, 13, 17],
        [ 3,  7, 11, 15, 19]])

### Practise

In [106]:
torch.manual_seed(seed= 0)


# Create a random tensor with shape (7, 7)
T1 = torch.rand((7,7))
T1.shape

T2 = torch.rand((1,7))

In [107]:
mm = torch.matmul(T1, T2.T)

In [108]:
mm

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [120]:
# seeding GPU
torch.manual_seed(1234)

R1 = torch.rand(size = (2,3)).to("cuda")
R2 = torch.rand((2,3)).to("cuda")

mm2 = torch.matmul(R1, R2.T)
print(f"The mm: {mm2}")



The mm: tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [ ]:
mm2.max()


tensor(0.3647, device='cuda:0')

In [123]:
mm2.argmin()

tensor(0, device='cuda:0')

In [130]:
torch.manual_seed(7)
X = torch.rand((1, 1, 1, 10))
m = X.squeeze()

In [131]:
m

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [132]:
print(f"first tensor {X} and it's shape {X.shape}")
print(f"second tensor {m} and it's shape {m.shape}")

first tensor tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) and it's shape torch.Size([1, 1, 1, 10])
second tensor tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) and it's shape torch.Size([10])
