In [27]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
torch.__version__


'2.7.1+cu128'

In [28]:
torch.cuda.is_available()
torch.cuda.device_count()

1

### Understanding Tensors

In [29]:
# scalar - 0 dim tensor
scalar = torch.tensor(6)
print(f"The tensor is of {scalar.ndim} dim")

The tensor is of 0 dim


In [30]:
scalar.item() # retrieves the number

6

In [31]:
vector = torch.tensor([2,3])
vector.shape         # hint: the num of dims is the num of brackets

torch.Size([2])

In [32]:
mat = torch.tensor([[1,2],
                    [3,4]])
mat.shape

torch.Size([2, 2])

In [33]:
ten = torch.tensor([[[1, 2, 2],
                    [3, 4, 3]]])
ten.shape  # goes from outer to inner

torch.Size([1, 2, 3])

Reminder: Tensor is an n dimsional array of numbers. So matrix, vectors, scalars are also tensors of different dims

In [34]:
ten

tensor([[[1, 2, 2],
         [3, 4, 3]]])

In [35]:
# creating a random tensor
rand_T = torch.rand((3,3))
rand_T

tensor([[0.8549, 0.5509, 0.2868],
        [0.2063, 0.4451, 0.3593],
        [0.7204, 0.0731, 0.9699]])

In [36]:
IM = torch.rand((224, 224, 3))
IM

tensor([[[0.1078, 0.8829, 0.4132],
         [0.7572, 0.6948, 0.5209],
         [0.5932, 0.8797, 0.6286],
         ...,
         [0.4758, 0.5401, 0.3012],
         [0.3814, 0.6282, 0.5399],
         [0.1416, 0.1422, 0.7317]],

        [[0.8814, 0.9635, 0.8055],
         [0.7877, 0.7096, 0.8370],
         [0.3718, 0.5773, 0.7018],
         ...,
         [0.6769, 0.7426, 0.2120],
         [0.7741, 0.9166, 0.7711],
         [0.9027, 0.2824, 0.7119]],

        [[0.3094, 0.3756, 0.9827],
         [0.4630, 0.5218, 0.5351],
         [0.5565, 0.2825, 0.8671],
         ...,
         [0.2341, 0.4463, 0.2069],
         [0.2815, 0.3703, 0.5340],
         [0.2222, 0.2361, 0.1357]],

        ...,

        [[0.0755, 0.1923, 0.7472],
         [0.7093, 0.5914, 0.9732],
         [0.8207, 0.8037, 0.7533],
         ...,
         [0.6247, 0.3102, 0.2898],
         [0.7181, 0.7118, 0.3500],
         [0.6217, 0.9026, 0.6079]],

        [[0.2616, 0.1576, 0.5076],
         [0.2175, 0.5825, 0.9111],
         [0.

In [37]:
tem = torch.arange(0, 101, 20, dtype = None)
print(tem)
co = torch.ones_like(tem)

tensor([  0,  20,  40,  60,  80, 100])


In [38]:
co

tensor([1, 1, 1, 1, 1, 1])

1. torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

2. Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

3. torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

4. torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

5. torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
torch.permute(input, dims)

6. torch.permute(input, dims) Rearrange the axis order

In [39]:
x = torch.arange(1, 20, 2)
x.shape

torch.Size([10])

In [40]:
x = x.reshape(5,2)

In [41]:
z = x.view(10,1)        # z is just a new view of x and changing z changes x
z

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])

In [42]:
print(f"Before squeeze the dims was {z.shape}")

k = z.squeeze()     # removes single dims
print(f"after sqeeze the dims: {k.shape}, the singles dims were removed")

Before squeeze the dims was torch.Size([10, 1])
after sqeeze the dims: torch.Size([10]), the singles dims were removed


In [43]:
print(f"Before permuting {x}\n")


print(f"after permuting {x.permute(1,0)}")

Before permuting tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]])

after permuting tensor([[ 1,  5,  9, 13, 17],
        [ 3,  7, 11, 15, 19]])


### Practise

In [44]:
torch.manual_seed(seed= 0)


# Create a random tensor with shape (7, 7)
T1 = torch.rand((7,7))
T1.shape

T2 = torch.rand((1,7))

In [45]:
mm = torch.matmul(T1, T2.T)

In [46]:
mm

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [47]:
# seeding GPU
torch.manual_seed(1234)

R1 = torch.rand(size = (2,3)).to("cuda")
R2 = torch.rand((2,3)).to("cuda")

mm2 = torch.matmul(R1, R2.T)
print(f"The mm: {mm2}")



The mm: tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [48]:
mm2.max()


tensor(0.5617, device='cuda:0')

In [49]:
mm2.argmin()

tensor(0, device='cuda:0')

In [50]:
torch.manual_seed(7)
X = torch.rand((1, 1, 1, 10))
m = X.squeeze()

In [51]:
m

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [52]:
print(f"first tensor {X} and it's shape {X.shape}")
print(f"second tensor {m} and it's shape {m.shape}")

first tensor tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) and it's shape torch.Size([1, 1, 1, 10])
second tensor tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) and it's shape torch.Size([10])
